export const kpiData = {
  revenue: { value: 2847, change: 12.3, label: "Revenue", prefix: "$" },
  orders: { value: 127, change: 8.1, label: "Orders", prefix: "" },
  roas: { value: 3.2, change: 0.4, label: "ROAS", prefix: "", suffix: "x" },
  spend: { value: 890, change: 5.2, label: "Ad Spend", prefix: "$" },
};

export const trendData = [
  { day: "Mon", revenue: 380, spend: 120, orders: 16 },
  { day: "Tue", revenue: 420, spend: 125, orders: 18 },
  { day: "Wed", revenue: 350, spend: 115, orders: 14 },
  { day: "Thu", revenue: 490, spend: 135, orders: 21 },
  { day: "Fri", revenue: 410, spend: 128, orders: 17 },
  { day: "Sat", revenue: 520, spend: 140, orders: 23 },
  { day: "Sun", revenue: 470, spend: 132, orders: 20 },
];

export const campaigns = [
  {
    id: "1",
    name: "Bluetooth Earbuds US",
    product: "Pro Max Earbuds",
    status: "active" as const,
    roas: 3.8,
    spend: 342,
    revenue: 1094,
    orders: 47,
    cpa: 7.28,
    dailyBudget: 50,
    startDate: "2026-03-10",
    market: "United States",
    healthTag: "top",
    creatives: [
      { id: "c1", name: "Creative A", headline: "Premium Sound, Zero Compromise", ctr: 2.8, roas: 3.8, status: "top" as const, image: "🎧" },
      { id: "c2", name: "Creative B", headline: "Never Miss a Beat", ctr: 1.2, roas: 1.9, status: "low" as const, image: "🎵" },
      { id: "c3", name: "Creative C", headline: "Music Without Limits", ctr: 2.1, roas: 3.1, status: "ok" as const, image: "🔊" },
    ],
    audienceBreakdown: [
      { segment: "25-28M", percentage: 38, roas: 4.2 },
      { segment: "29-34M", percentage: 26, roas: 3.1 },
      { segment: "25-28F", percentage: 17, roas: 2.8 },
      { segment: "35-44M", percentage: 12, roas: 1.4 },
      { segment: "Other", percentage: 7, roas: 0.9 },
    ],
    performanceHistory: [
      { date: "Mar 10", spend: 48, revenue: 120, roas: 2.5 },
      { date: "Mar 12", spend: 50, revenue: 155, roas: 3.1 },
      { date: "Mar 14", spend: 50, revenue: 142, roas: 2.8 },
      { date: "Mar 16", spend: 49, revenue: 178, roas: 3.6 },
      { date: "Mar 18", spend: 50, revenue: 190, roas: 3.8 },
      { date: "Mar 20", spend: 48, revenue: 185, roas: 3.9 },
      { date: "Mar 22", spend: 50, revenue: 195, roas: 3.9 },
      { date: "Mar 24", spend: 50, revenue: 180, roas: 3.6 },
      { date: "Mar 26", spend: 49, revenue: 192, roas: 3.9 },
      { date: "Mar 28", spend: 50, revenue: 200, roas: 4.0 },
    ],
  },
  {
    id: "2",
    name: "Yoga Pants EU",
    product: "FlexFit Leggings",
    status: "active" as const,
    roas: 4.1,
    spend: 280,
    revenue: 1148,
    orders: 52,
    cpa: 5.38,
    dailyBudget: 40,
    startDate: "2026-03-05",
    market: "Europe",
    healthTag: "top",
    creatives: [],
    audienceBreakdown: [],
    performanceHistory: [],
  },
  {
    id: "3",
    name: "Phone Cases US",
    product: "UltraShield Case",
    status: "active" as const,
    roas: 2.8,
    spend: 156,
    revenue: 437,
    orders: 31,
    cpa: 5.03,
    dailyBudget: 25,
    startDate: "2026-03-15",
    market: "United States",
    healthTag: "ok",
    creatives: [],
    audienceBreakdown: [],
    performanceHistory: [],
  },
  {
    id: "4",
    name: "Earbuds Accessories UK",
    product: "SilicTip Pro Pack",
    status: "active" as const,
    roas: 3.5,
    spend: 112,
    revenue: 392,
    orders: 28,
    cpa: 4.0,
    dailyBudget: 20,
    startDate: "2026-03-18",
    market: "United Kingdom",
    healthTag: "ok",
    creatives: [],
    audienceBreakdown: [],
    performanceHistory: [],
  },
  {
    id: "5",
    name: "LED Desk Lamp DE",
    product: "LumiPro Desk Light",
    status: "paused" as const,
    roas: 0.8,
    spend: 95,
    revenue: 76,
    orders: 4,
    cpa: 23.75,
    dailyBudget: 30,
    startDate: "2026-03-01",
    market: "Germany",
    healthTag: "paused",
    creatives: [],
    audienceBreakdown: [],
    performanceHistory: [],
  },
];

export const actionItems = [
  {
    id: "a1",
    type: "creative_fatigue" as const,
    campaign: "Bluetooth Earbuds US",
    campaignId: "1",
    message: 'Creative fatigue detected — CTR dropped 23% in 3 days',
    suggestion: "Generate 3 new creative variants to replace fatigued assets",
    severity: "warning" as const,
  },
];

export const agentSuggestion = {
  message: "This week's overall ROAS improved 15%. I recommend increasing the Yoga Pants EU daily budget by $20 for scaling. Based on audience data, 25-34F segment shows strong conversion potential.",
  actions: ["Execute", "Later"],
};

export const creativeVariants = [
  { id: "v1", headline: "Premium Sound, Zero Compromise", body: "Experience crystal-clear audio with our Pro Max Earbuds. 40hr battery. ANC 3.0.", ctr: 2.1, tone: "Premium", image: "🎧", status: "live" as const },
  { id: "v2", headline: "Never Miss a Beat", body: "Your workout deserves better sound. Sweat-proof, 40hr battery, deep bass.", ctr: 2.8, tone: "Active", image: "🏃", status: "live" as const },
  { id: "v3", headline: "Music Without Limits", body: "From commute to gym — one pair that does it all. Free shipping today.", ctr: 1.9, tone: "Casual", image: "🎵", status: "draft" as const },
  { id: "v4", headline: "Sound That Moves You", body: "Engineered for life on the go. Premium drivers. All-day comfort.", ctr: 2.4, tone: "Premium", image: "✨", status: "draft" as const },
  { id: "v5", headline: "50% Off — Today Only", body: "Limited time: Get our best-selling earbuds at half price. Don't wait.", ctr: 3.2, tone: "Urgency", image: "🔥", status: "draft" as const },
];

export const assetLibrary = [
  { id: "a1", name: "Earbuds Hero Shot", type: "image", status: "live" as const, usedIn: 2 },
  { id: "a2", name: "Lifestyle — Gym", type: "image", status: "live" as const, usedIn: 1 },
  { id: "a3", name: "Product — White BG", type: "image", status: "draft" as const, usedIn: 0 },
  { id: "a4", name: "Yoga Pants — Studio", type: "image", status: "live" as const, usedIn: 1 },
  { id: "a5", name: "Phone Case — Lifestyle", type: "image", status: "used" as const, usedIn: 0 },
  { id: "a6", name: "Earbuds — Unboxing", type: "image", status: "used" as const, usedIn: 0 },
];
